### ISSUE TITLE
animation glitch on 1.2

### ISSUE THREAD

**Issue by keesoudwater34** [PredatorCZ/XenoMax#10]
there seems to be an animation glitch related to the tool that will break it during export. the 1.1 does it normally but the 1.2 seems to crumple the first frame and the rest works fine and sometimes like the instance ill add here add other frames to it. it cant be from animation export in general since the skell animations with havok has worked fine other than a couple instances but those are unrelated to  the export of the model. 
[Elma Run animations.zip](https://github.com/PredatorCZ/XenoMax/files/4332373/Elma.Run.animations.zip)

**Comment by PredatorCZ** [comment]
I have no idea what is your problem you're having. I checked animations and they are same. The range is [0, 20], I have noticed, that v1.2 test file have 2 animations loaded (first was some idle, 2nd was running loaded onto it). I encourage you to not load animations on each other, always delete all keys before loading animation.

**Comment by keesoudwater34** [comment]
if you check in blender there should be a frame that is called frame 0 that croumples into a big mess and if it doesnt show ill rerun them and provide pictures

**Comment by PredatorCZ** [comment]
Loaded your fbx files in UE4, no problems whatsoever, only v1.1 had glitched excess frames at the end, thats all. 
![yabba_elma_ue4_fml](https://user-images.githubusercontent.com/18037167/82797480-6ae65c00-9e77-11ea-84b3-9c9070873bd7.gif)
