### ISSUE TITLE
UV map non existent for shadowing around eyes on X caracters.

### ISSUE THREAD

**Issue by keesoudwater34** [PredatorCZ/XenoMax#13]
simply put there is a mesh around the inside of the eye that for some odd reason doesnt get its uv mapping.  provided are the files needed to pull the face and the exported fbx from there ive already compiled the whole body of. material sha1 for irina. and texture eyeb i believe. also happend on lin and think its so with everyone else.
[Irina Face.zip](https://github.com/PredatorCZ/XenoMax/files/4670466/Irina.Face.zip)

**Comment by PredatorCZ** [comment]
There are several meshes. I will point materials they are linked to:
eye: the eye itself
eyeb: here is the first 'shadow' you refer to, and uv's are intact here, however this looks more like an eyeball
sha1: they don't have uv channels, but 'shadows' are stored inside vertex alpha channel
To me, this is perfectly fine. Not all objects needs to have a texture attached onto it.

**Comment by keesoudwater34** [comment]
at this point im thinking the eyeball is suposed to be cut out and useses the eye b as the white background. its wierd how that is setup though.

i think youre right on that but eye b seems to be the shadow map like you said. its just using a lot of  alphas. i just dont know what the use of that mesh would be to be honest. or how it can be used
