### ISSUE TITLE
Building Project Errors

### ISSUE THREAD

**Issue by nanogram** [PredatorCZ/XenoMax#17]
When trying to build the project, everything load until the end where it can't find three specific files, not sure where they are.

Error	C1083	Cannot open include file: 'matrix3.h': No such file or directory
Error	C1083	Cannot open include file: 'iparamb2.h': No such file or directory
Error	C1083	Cannot open include file: 'IPathConfigMgr.h': No such file or directory

**Comment by PredatorCZ** [comment]
Have you installed SDK?

**Comment by nanogram** [comment]
I am building it with VS2019 and have the 2015 tools & cmake installed as well. Not sure if there was anything else that was needed.

**Comment by PredatorCZ** [comment]
You need to install 3ds max SDK for the max version you're using.
SDK is included within regular 3ds max installer.

**Comment by nanogram** [comment]
I think I also might need C++ MFC as well, seeing that this is the last error I'm getting:
`Error	RC1015	cannot open include file 'afxres.h'.`

**Comment by PredatorCZ** [comment]
You don't, you can change `afxres.h` for `winres.h` in rc file.

**Comment by nanogram** [comment]
Yup ok now everything compiles correctly, thank you!
