### ISSUE TITLE
Failure to extract textures | Xenoblade X

### ISSUE THREAD

**Issue by PipPipPin** [PredatorCZ/XenoMax#19]
XenoMax successfully extracts textures for all other models I have tried, but some simply don't extract.

Thus far, I have successfully used it to extract all textures contained in chr_np.cpk and chr_oj.cpk, with no errors.
This error only occurs with map.cpk textures. 

VGMT->(ma9990.casmhd)XenoToolset(casmExtract)->(anyCamdo)3DSMax(2013)
VGMT->(ma9990.casmhd)XenoToolset(casmExtract)->(anyCamdo)XenoToolset(mdoTextureExtract)
Both of these workflows produce no textures. XenoToolset(casmExtract) produced a folder with textures, but they are not tied to the model (both workflows produced a folder matching the model in other cases), requiring me to setup materials for every model while surfing through a veritable haystack of textures. XenoToolset(mdoTextureExtract) produced a log stating that an MXMD was detected, but no other output.

I have tried CLI for all of these, with no difference, irregardless of the arguments used.

These workflows work fine in places where VGMT was the only tool needed to extract the camdo files. 

I have also attempted to use the XenoLibToolset. It works perfectly for extracting bdat, but all other uses produce an "ERROR: string too long" in the log. I am aware that that issue has been reported on its issue tracker, but figured it may help to provide all info I've encountered trying to solve this.

**Comment by PredatorCZ** [comment]
`string too long` is related to https://github.com/PredatorCZ/XenoLib/issues/5 and it should be fixed in 2nd preview.
If I remember correctly, maps are using only external textures. There aren't any in camdo files and they don't have names.

**Comment by PipPipPin** [comment]
Ah, I was operating under the assumption that the casmt files accompanying each camdo were the textures for their respective camdo, that I could extract them and isolate whatever textures with their respective model. IE extract ma9990/objects/0.camdo and 0.casmt to help with identifying which textures belond where.

Closing issue! Thanks for the assist!
