### ISSUE TITLE
Face Morphs Issue

### ISSUE THREAD

**Issue by ChaoticFusion40** [PredatorCZ/XenoMax#2]
The Face Is Dropping In 3DS Max 2017 With Mythra And Rex

**Comment by PredatorCZ** [comment]
This happens, when morph modifier is above skin one, cause is unknown, probably 3ds max internal.
Did you reevaluated any said modifiers?

**Comment by ChaoticFusion40** [comment]
> This happens, when morph modifier is above skin one, cause is unknown, probably 3ds max internal.
> Did you reevaluated any said modifiers?

no

**Comment by PredatorCZ** [comment]
Tested on 2017, 2012, both mythra and rex, no problems whatsoever.
