### ISSUE TITLE
Importing .wimdo models into 3ds max 2015 crashes the program

### ISSUE THREAD

**Issue by Andree12** [PredatorCZ/XenoMax#3]
Everytime I tried to import with the 3ds max 2015 program, it either closes by itself or receives a error.
Can you test this, if it doesn't happen to you, it is me.

**Comment by PredatorCZ** [comment]
Which files specifically causes problem?
Would you be able to provide minidump file?
Does it occur for older versions?

**Comment by Andree12** [comment]
> Which files specifically causes problem?
> Would you be able to provide minidump file?
> Does it occur for older versions?

1. Any .wimdo file
2.  I'll PM the file to you.
3. Not sure.

**Comment by PredatorCZ** [comment]
Loading models for versions 2014 and 2015 crashes program.
I have no idea what can cause this problem. It's some internal bug, that lasted for 2 versions.
I might remove model loading support because of this.

**Comment by Andree12** [comment]
Closing this down, PredatorCZ is working on a new toolset that replaces XenoMax.
