### ISSUE TITLE
Request: Morphs as Separate meshes 

### ISSUE THREAD

**Issue by ChaoticFusion40** [PredatorCZ/XenoMax#4]
I would like to make a request to add a feature that the morphs would become seperate meshes with names like (ObjectXX_morph name), this feature would be nice if someone ports the models to xnalara. the morph in one model would remain as well.

**Comment by PredatorCZ** [comment]
You can control morph channels from maxscript, if you want to use export from here.
Simply set one channel to 100% and export mesh, it depends on exporter, whenever mesh will be converted into pure mesh, or keeps it's entire morph controller.

**Comment by ChaoticFusion40** [comment]
feel free to close this issue

**Comment by ChaoticFusion40** [comment]
what options in 3ds max do i choose.

**Comment by ChaoticFusion40** [comment]
never mind.

**Comment by ChaoticFusion40** [comment]
closing.
