### ISSUE TITLE
Importing waist/torso models crashes 3DSMax

### ISSUE THREAD

**Issue by ryanbevins** [PredatorCZ/XenoMax#6]
As stated, importing waist/torso models crashes 3DSMax(specifically Xenoblade X Elma models tagged with ID 221 at the end, untested with others, with an index of 12 as the indicator of it being a waist/torso model)

**Comment by ryanbevins** [comment]
(worth mentioning that your original 3dsmax script works fine for importing these models)

**Comment by PredatorCZ** [comment]
The issue has been fixed in version 1.2.
Please verify and close this issue, if everything is ok.
