### ISSUE TITLE
Weight Paints Non Existent when exported

### ISSUE THREAD

**Issue by keesoudwater34** [PredatorCZ/XenoMax#8]
the weight paints on object oj300041 ( On X ) when exported dont exist and its the same on a mate of mine's. everything else has worked in the past so im clueless of what it can be. acress difrent formats and all it doesnt do it and i got no clue on it anymore so i think it meight be something that gets screwed up in the tool but arent sure. done in 2017 3ds max

**Comment by PredatorCZ** [comment]
When exporting to the FBX, check Animations, Deformations and Skins.
Tested, worked.

**Comment by keesoudwater34** [comment]
still the same result. i dont know how or why but ill just send the files for it cause it still doesnt give vertex groups with those settings


https://fiIemaiI.com/d/agqzsvwbbzjshxt



![3ds Export settings](https://user-images.githubusercontent.com/50651160/73530198-4f62cb80-4418-11ea-8b5b-a27e00a76472.jpg)

**Comment by keesoudwater34** [comment]
i ran the old decraptated tool through the model and it exported just fine. transferred it to it other rig but its still strange how it doesnt do it cause that excludes the 3ds max exports

**Comment by PredatorCZ** [comment]
I had imported the fbx file you provided, everything works fine. so is it some kinda specific problem?

**Comment by keesoudwater34** [comment]
hmm ill leave this open for now ill do some more tests soon but the wierd thing is i was not the only one that had that probem thats whats so strange

**Comment by keesoudwater34** [comment]
what items would you need to diagnose this sorry for the late reaction

**Comment by keesoudwater34** [comment]
it also just happend on skell dl019600 no weight paints

**Comment by PredatorCZ** [comment]
You import it to a blender? What happens, when you import it to a 3ds max?

**Comment by keesoudwater34** [comment]
in 3ds max it does have weight paints as far as i could tell but in blender it has none. its only with specific models that happens, it also happens on v1.2 of the tool as far as i could remember. its like some parameter is not there. 

**EDIT** more explanation.  in vertex groups there are none when the same is imported from max to blender. the one in max was exported to fbx and then reimported to see if the weights were there


![Weights In 3ds max](https://user-images.githubusercontent.com/50651160/76846698-36d03880-6841-11ea-95a6-9d53154cf84b.jpg)
![Weights In Blender](https://user-images.githubusercontent.com/50651160/76846707-3899fc00-6841-11ea-96d7-614b0b19c854.jpg)

**Comment by PredatorCZ** [comment]
Is there some kind of message output, like console, error log? What does it say?

**Comment by keesoudwater34** [comment]
i cant even find an console log ive been looking for a while on 3ds max where to find it

**Comment by PredatorCZ** [comment]
I mean in blender.
If I remember correctly, there should be an option that will enable console log.
But I haven't spent much time in Blender, so I don't know how FBX is logging things.

**Comment by PredatorCZ** [comment]
I had exported my own FBX and loaded it into UE4, weights are fine. Seems like a bug in Blender.
![yabba_skel_ue4_fml](https://user-images.githubusercontent.com/18037167/82799747-d0881780-9e7a-11ea-9e32-8020823cc9bc.jpg)

**Comment by keesoudwater34** [comment]
i was able to redcon it but its like my 3ds max is having issues wiht it somewhat.cause i remember reimporting it into 3ds max and it just being gone for some odd reason. im asking help on reddit and the max forum first on some other stuff but ill keep this open just in case. ill run some more tests down the line though

**Comment by PredatorCZ** [comment]
What FBX version are you using?

**Comment by keesoudwater34** [comment]
when i exported it i tried i believe 2015 till 2017 but all the same issues. im also installing max 2017 service pack 3 right now cause the things is having more problems than it should

**Comment by keesoudwater34** [comment]
nothing got fixed i dont think. i even reinstalled it compleetly the program and the problems still stay. its the fbx import and exporter thats going nuts for some reason and ive ran some test files of importing straight known good fbx's and exporting them and it still fucks em up wierdly. i dont know if i can ask this of you predator but can i ask you to help me figure this out somewhat? cause i dont know the max system too well to figure out whats going on with it. im serieusly thinking the fbx plugin thats on default max is busted.

**Comment by PredatorCZ** [comment]
I had tested your fbx files in the past, and they worked fine. You could test them elsewhere, Unity/UE4/Noesis or anything that load FBX files basically. Or/and you can send me screens of your settings in the FBX exporter.

**Comment by keesoudwater34** [comment]
ill run the skell through later but this is one of the things that break with the morphs/shapekeys. right is the xenomax 1.2 and on the left is the old mzd tool. old tool works fine and new just breaks on student version 3ds max 2017 and im not the only one that got that problem. a friend of mine got the same. skins and morphs have always been enabled. this is in unity

![3ds max export settings](https://user-images.githubusercontent.com/50651160/83079286-cb45eb00-a07b-11ea-8a87-fa88d1265c4a.png)


![shape fucked](https://user-images.githubusercontent.com/50651160/83078758-94bba080-a07a-11ea-91e7-dd11b6caf10e.gif)

**Comment by PredatorCZ** [comment]
You are correct. Morphs are fucked on export. It's problem inside Morph modifier.
I tested skell in Noesis, it works here too, with animations.

**Comment by keesoudwater34** [comment]
skell animations i usually dont have throuble with on xenomax and its also the xeno 2 caracters that break with morphs. rex had the same. but for some reason the new tool doesnt like to do it. and thats the thing i dont know it is any difrent. i will run through the ares skell again see if it pops up with v1.2. rigs work fine univerally but if i find the rig is gone on that skell ill also import it into unity and if i can figure out noesis ill try there too

**Comment by PredatorCZ** [comment]
You can also check if morphs are broken on older versions as well.

**Comment by keesoudwater34** [comment]
Blender stock Importer
![image](https://user-images.githubusercontent.com/50651160/83138560-42669800-a0eb-11ea-9b12-72f75c4513dd.png)

blender with paid better importer
![image](https://user-images.githubusercontent.com/50651160/83138713-8194e900-a0eb-11ea-943f-cfeefbe7ca09.png)

Unity
![image](https://user-images.githubusercontent.com/50651160/83138819-aa1ce300-a0eb-11ea-8692-a9bd034fb963.png)


i bought the new importer yesterday almost regretted it too but it seems to work for the skell. but shapekeys doesnt fix it

**Comment by CosmicDreamsOfCode** [comment]
> ill run the skell through later but this is one of the things that break with the morphs/shapekeys. right is the xenomax 1.2 and on the left is the old mzd tool. old tool works fine and new just breaks on student version 3ds max 2017 and im not the only one that got that problem. a friend of mine got the same. skins and morphs have always been enabled. this is in unity
> 
> ![3ds max export settings](https://user-images.githubusercontent.com/50651160/83079286-cb45eb00-a07b-11ea-8a87-fa88d1265c4a.png)
> 
> ![shape fucked](https://user-images.githubusercontent.com/50651160/83078758-94bba080-a07a-11ea-91e7-dd11b6caf10e.gif)

Do you still have that MZD tool? Unless theres another fix for exporting morphs...

**Comment by PredatorCZ** [comment]
I've looked into morph problems some time ago, it's an internal bug within Morpher Modifier API. There is no easy way to fix them as of now.

**Comment by CosmicDreamsOfCode** [comment]
Got a friend to send me a very old version of the importer from when it was still a script.
Morphs work perfectly there, in fact they might even work better than the plugin one in general...
